### ISSUE TITLE
installation of v2.143.0 rpm from advisory=FEDORA-2020-04374575bf doesn't seem to be using updated policy from this repo

### ISSUE THREAD

**Issue by dweomer** [containers/container-selinux#101]
Trying to validate the RPM installation on Fedora 32 for the recently tagged v2.143.0 as described [on bodhi](https://bodhi.fedoraproject.org/updates/FEDORA-2020-04374575bf):
```
dnf upgrade --enablerepo=updates-testing --advisory=FEDORA-2020-04374575bf
```
**_And it does not seemed to have picked up the policy in this repo._** 

This Vagrantfile is my validation harness: https://github.com/containerd/containerd/blob/586061508e1dd1ba5305778265f967ba5a409bcc/Vagrantfile
After spinning up the VM via `vagrant up` I connect to it and run the installation line from bodhi, and seemingly have the correct RPM via `dnf info container-selinux`:
```
Last metadata expiration check: 0:02:59 ago on Fri 07 Aug 2020 11:39:21 PM UTC.
Installed Packages
Name         : container-selinux
Epoch        : 2
Version      : 2.143.0
Release      : 1.fc32
Architecture : noarch
Size         : 45 k
Source       : container-selinux-2.143.0-1.fc32.src.rpm
Repository   : @System
From repo    : updates-testing
Summary      : SELinux policies for container runtimes
URL          : https://github.com/containers/container-selinux
License      : GPLv2
Description  : SELinux policy modules for use with container runtimes.
```
I then run the `test-cri` provisioner with SELinux Enforcing invoking:
```
SELINUX=Enforcing vagrant up --provision-with=selinux,test-cri
```
This starts containerd and then runs critest against it. Prior to my fix that should be in v2.143.0 I would see critest suite failures like this:
```
    default: Summarizing 11 Failures:
    default: 
    default: [Fail] 
    default: [k8s.io] Security Context NamespaceOption [It] runtime should support HostPID 
    default: /root/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/container.go:389
    default: [Fail] [k8s.io] Security Context NamespaceOption [It] runtime should support ContainerPID 
    default: /root/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/container.go:389
    default: 
    default: [Fail] [k8s.io] Multiple Containers [Conformance] when running multiple containers in a pod [It] should support container exec 
    default: /root/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/container.go:389
    default: 
    default: [Fail] [k8s.io] Security Context NamespaceOption [It] runtime should support PodPID 
    default: /root/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/container.go:389
    default: 
    default: [Fail] 
    default: [k8s.io] Streaming runtime should support streaming interfaces [It] runtime should support portforward in host network 
    default: /root/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/networking.go:253
    default: 
    default: [Fail] [k8s.io] Multiple Containers [Conformance] when running multiple containers in a pod 
    default: [It] should support network 
    default: /root/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/networking.go:253
    default: 
    default: [Fail] [k8s.io] Networking runtime should support networking [It] runtime should support port mapping with host port and container port [Conformance] 
    default: /root/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/networking.go:253
    default: 
    default: [Fail] [k8s.io] Security Context NamespaceOption 
    default: [It] runtime should support HostIpc is true 
    default: /root/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/security_context_linux.go:159
    default: 
    default: [Fail] [k8s.io] Streaming runtime should support streaming interfaces [It] runtime should support portforward [Conformance] 
    default: /root/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/networking.go:253
    default: 
    default: [Fail] 
    default: [k8s.io] Networking runtime should support networking [It] runtime should support port mapping with only container port [Conformance] 
    default: /root/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/networking.go:253
    default: 
    default: [Fail] [k8s.io] Multiple Containers [Conformance] when running multiple containers in a pod [It] should support container log 
    default: /root/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/multi_container_linux.go:95
    default: 
    default: Ran 88 of 95 Specs in 246.619 seconds
    default: FAIL! -- 77 Passed | 11 Failed | 0 Pending | 7 Skipped
```
**And this is what I still see with this RPM installed. This is surprising to me**. When I install the policy from this repo via source (after installing `selinux-policy-devel` and `bzip2`) by running `make && sudo make install-policy` I get the results that I expect, e.g.:
```
    default: Summarizing 1 Failure:
    default: 
    default: [Fail] [k8s.io] Security Context NamespaceOption 
    default: [It] runtime should support HostIpc is true 
    default: /root/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/security_context_linux.go:159
    default: 
    default: Ran 88 of 95 Specs in 65.534 seconds
    default: FAIL! -- 87 Passed | 1 Failed | 0 Pending | 7 Skipped
```
Is there something wrong with how the RPM is being build? This build log seems to indicate that the wrong tag is being used: https://kojipkgs.fedoraproject.org//packages/container-selinux/2.143.0/1.fc32/data/logs/noarch/build.log
